### ISSUE TITLE
编译出错了哦

### ISSUE THREAD

**Issue by x-i-ao-b-ai** [kitech/qt.inline#1]
/usr/include/qt/QtCore/qatomic_x86.h:107:30: error: redefinition of 'QAtomicOps'
template <typename T> struct QAtomicOps : QBasicAtomicOps<sizeof(T)>
                             ^
/usr/include/qt/QtCore/qatomic_cxx11.h:89:30: note: previous definition is here
template <typename X> struct QAtomicOps
                             ^
In file included from /home/xiaobai/Work/rust/qt.inline/src/core/qatomic_x86.cxx:14:
/usr/include/qt/QtCore/qatomic_x86.h:114:19: error: redefinition of 'QAtomicOpsSupport<1>'
template<> struct QAtomicOpsSupport<1> { enum { IsSupported = 1 }; };
                  ^~~~~~~~~~~~~~~~~~~~
/usr/include/qt/QtCore/qatomic_cxx11.h:65:19: note: previous definition is here
template<> struct QAtomicOpsSupport<1> { enum { IsSupported = 1 }; };
                  ^
In file included from /home/xiaobai/Work/rust/qt.inline/src/core/qatomic_x86.cxx:14:
/usr/include/qt/QtCore/qatomic_x86.h:115:19: error: redefinition of 'QAtomicOpsSupport<2>'
template<> struct QAtomicOpsSupport<2> { enum { IsSupported = 1 }; };

**Comment by kitech** [comment]
应该是个qt5.6引起的，现在的代码还是qt5.5时测试的。
这些代码需要好好搞下兼容性，有用了不该用的头文件。

**Comment by kitech** [comment]
too long time. now big changed wrapper and with ci.
