### ISSUE TITLE
Why are you uploading built libraries to vim-cn?

### ISSUE THREAD

**Issue by lilydjwg** [kitech/qt.inline#6]
Recently I've received a lot of libQt5inline.{so,dll,dll.a,dylib} files, occupying a lot of disk space but it seems that no one is ever downloading those. So what's the purpose in doing so?

**Comment by kitech** [comment]
The project's travis CI script automatic do that.
When I need release a version, I will download the binary release files from vim-cn site.
My archlinux not suitable for build binary release. It's packages is too new.
Sorry for occpuying a lot disk space.  These days update often.
So lazy not move to other binary release service.
I will reconfigure only upload for release build, about 200M per release.
Any way, Thanks all.

**Comment by lilydjwg** [comment]
OK, so a 7-day cleanup should not disrupt things, right?

**Comment by kitech** [comment]
Enough, thanks.
